name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify installation
      run: |
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Workspaces found:"
        npm run --workspaces --if-present --silent list
        
    - name: Build shared package
      run: npm run build --workspace=shared
      
    - name: TypeScript checks
      run: npm run typecheck
      
  notify:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
    - name: Notify on success
      if: needs.test.result == 'success'
      run: |
        echo "✅ CI Pipeline completed successfully!"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        
    - name: Notify on failure
      if: needs.test.result == 'failure'
      run: |
        echo "❌ CI Pipeline failed!"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        exit 1