name: CI - Fast

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify installation
      run: |
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Workspaces found:"
        npm run --workspaces --if-present --silent list
        
    - name: Build shared package
      run: npm run build --workspace=shared
      
    - name: Build server package
      run: npm run build --workspace=server
      
    - name: Build client package
      run: npm run build --workspace=client
      
    - name: TypeScript checks
      run: npm run typecheck
      
    - name: ESLint checks
      run: npm run lint
      
    - name: Jest unit tests
      run: npm run test
      
    - name: Upload any test artifacts (if they exist)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts-${{ github.run_id }}
        path: |
          test-results/
          playwright-report/
        if-no-files-found: ignore
        retention-days: 30
      
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && needs.test.result == 'success'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build shared package
      run: npm run build --workspace=shared
      
    - name: Build client for production
      run: npm run build --workspace=client
      
    - name: Deploy to Vercel
      working-directory: packages/client
      run: |
        npm install vercel --save-dev
        mkdir -p .vercel
        echo '{"orgId":"${{ secrets.VERCEL_ORG_ID }}","projectId":"${{ secrets.VERCEL_PROJECT_ID }}"}' > .vercel/project.json
        npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes

  notify:
    runs-on: ubuntu-latest
    needs: [test, deploy]
    if: always()
    steps:
    - name: Notify Slack on deployment success
      if: needs.test.result == 'success' && needs.deploy.result == 'success'
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"🚀 *Fast CI + Deployed to Production*\n• Branch: `${{ github.ref_name }}`\n• Commit: `${{ github.sha }}`\n• Author: ${{ github.actor }}\n• <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Notify Slack on test success only
      if: needs.test.result == 'success' && needs.deploy.result == 'skipped'
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"✅ *Fast CI Pipeline Success*\n• Branch: `${{ github.ref_name }}`\n• Commit: `${{ github.sha }}`\n• Author: ${{ github.actor }}\n• <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Notify Slack on deployment failure
      if: needs.test.result == 'success' && needs.deploy.result == 'failure'
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"❌ *Fast CI Deployment Failed*\n• Branch: `${{ github.ref_name }}`\n• Commit: `${{ github.sha }}`\n• Author: ${{ github.actor }}\n• Tests passed but deployment failed\n• <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Notify Slack on test failure
      if: needs.test.result == 'failure'
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"❌ *Fast CI Pipeline Failed*\n• Branch: `${{ github.ref_name }}`\n• Commit: `${{ github.sha }}`\n• Author: ${{ github.actor }}\n• <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}